### PR TITLE
Update to Drupal 7.40

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Instructions to test:

- Create a new Drupal 7 site for testing "d7test" (name to suit)
- Clone the git repository on your local system
- cd d7test
- git remote add drops-7 git@github.com:pantheon-systems/drops-7.git
- git fetch drops-7
- git merge drops-7/update-7.40
- git push origin master

Visit your site, step through the installer pages, visit the Status page, test basic functionality.

### CODE REVIEW

**Comment by craychee** [comment]
:+1: Here is the result of my test of this branch against a basic installation: https://circleci.com/gh/craychee/gmiw/47#commits

**Comment by greg-1-anderson** [comment]
That is super cool @craychee. Did you also test on Pantheon?

**Comment by craychee** [comment]
@greg-1-anderson I can do. Let's see how the deployment takes.

**Comment by craychee** [comment]
@greg-1-anderson success: https://circleci.com/gh/craychee/gmiw/48
You can see the resulting 7.4 repo here: http://dev-gosh-michelle-is-witty.pantheon.io/

**Comment by greg-1-anderson** [comment]
Excellent. I now know how to spell "walla".

**Pull request merged**
