### PR TITLE
Adding Drush Command for posting solr schema

### PR DESCRIPTION
**Pull request by stevector**
Fulfills https://github.com/pantheon-systems/drops-7/issues/82

@greg-1-anderson, I'm going to schedule a meeting for tomorrow for us to discuss how to test this functionality and other parts of the repo.

### CODE REVIEW

**Comment by amitaibu** [comment]
Hi @stevector !

Will this go in at a certain point, or should we for now create our own custom script that basically does the same?

**Comment by stevector** [comment]
@amitaibu! I think this PR could still eventually get merged. It would have to be tested and approved to then be released with a regular core release. (We try to limit the number of releases that come through the Pantheon dashboard) I saw you were chatting with @greg-1-anderson over in https://github.com/pantheon-systems/quicksilver-examples/issues/142. Does that get the job done for you?

**Comment by amitaibu** [comment]
@stevector !! 😄 

https://github.com/pantheon-systems/quicksilver-examples/issues/142 is actually another issue from Gizra, but not I was working on (thus, I don't care about it that much 😜), but I'll have to try it at a certain point.

This PR however seems to do the job for me - I'm now using it for a site creation script, where Solr is also configured.

**Comment by stevector** [comment]
Glad to know it is working for you! @greg-1-anderson, what do you think of merging this into a future release?

**Comment by greg-1-anderson** [comment]
Hm there's a release of Drupal 7 due out this Wednesday...

**Comment by greg-1-anderson** [comment]
Could you make this PR merge into the `default` branch @stevector ?

**Comment by greg-1-anderson** [comment]
... and rebase it off of HEAD of default?

**Comment by stevector** [comment]
Done! https://github.com/pantheon-systems/drops-7/pull/131

**Pull request closed without merging**
