### PR TITLE
Pressflow 7.36

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Drupal 7.36 from upstream, for testing.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Installed a site on my onebox; URL is:

http://dev-updatetest-736.onebox.pantheon.io/

**Comment by greg-1-anderson** [comment]
I have also done update testing via git push on a couple of sites.  No updatedb required this release.

**Comment by populist** [comment]
+1 from me. Looks like a normal Drupal update and my test on a production site from this branch worked great.

**Comment by ari-gold** [comment]
+1 
Just updated an existing site successfully.

**Pull request merged**
