### PR TITLE
Use specific permission for access to pantheon apache solr settings. …

### PR DESCRIPTION
**Pull request by nadavoid**
…Original work by jacintocapote and mrfelton.

Will resolve Issue #43.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Thanks for submitting this.  It would be helpful to have a hook_update_N to apply the new permission to any role that previously had `administer search`.

**Comment by nadavoid** [comment]
@greg-1-anderson Good idea. I just added an update hook that does that.

**Comment by greg-1-anderson** [comment]
Maybe use the APIs?

https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_role_permissions/7
https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_role_grant_permissions/7

**Comment by nadavoid** [comment]
Oh yes, certainly. I looked at those functions yesterday but misread what they did. I'll plan on doing that this evening (Pacific time).

**Comment by nadavoid** [comment]
The update function is updated to use the user API now. `user_roles()` is the function that I was wanting, along with `user_role_grant_permissions()`.

**Comment by nadavoid** [comment]
Hi @greg-1-anderson Is there anything you're looking for on this pull request before merging it? This issue keeps popping up and biting various developers.

**Comment by greg-1-anderson** [comment]
Anything that we merge to master shows up on the dashboard of all customers, so we only do this at the same time we're putting out a new Drupal 7 release.

**Comment by jucallme** [comment]
+1 thanks for this patch we need it, in our instance we have to keep the core Drupal search module enabled to run solr search.

**Pull request merged**
