### PR TITLE
Drops 7.43

### PR DESCRIPTION
**Pull request by mparker17**
This is a security update!

Merged [Drupal 7.43](https://www.drupal.org/drupal-7.43-release-notes). See also [the 8.0.4 release nodes](https://www.drupal.org/drupal-8.0.4).

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Thanks for this!  Not to appear ungrateful, but I re-created the PR via the automation script, so that it shows 'pantheon automation' as the author of the merge commit.  See #80.

**Comment by mparker17** [comment]
Sounds good, thanks @greg-1-anderson !

**Comment by dearmond** [comment]
When will this be merged into the master branch? All my build scripts pull from drops-7/master

**Comment by greg-1-anderson** [comment]
#80 will be merged shortly.  (#80 is the same as this PR)

**Pull request closed without merging**
