### PR TITLE
[CMSP-367] Upgrade default PHP version to 8.1

### PR DESCRIPTION
**Pull request by pwtyler**
Updates PHP to 8.1 in `pantheon.upstream.yml`. If PHP is set in `pantheon.yml`, this value is ignored.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
8.1 is supported: https://www.drupal.org/project/drupal/issues/3224299

8.2 issue is still "active": https://www.drupal.org/project/drupal/issues/3304807

**Comment by pwtyler** [comment]
On rebase & merge, this commit will push on to `master` and be made available on D7 dashboards _without_ waiting for another upstream release.

**Comment by CdrMarks** [comment]
@pwtyler should this be merged or closed?

**Comment by pwtyler** [comment]
- Needs changelog
- Holding for more w/ @scottbuscemi re: plans for PHP8.

**Comment by scottbuscemi** [comment]
We'll tackle this as part of the CMS & PHP Upgrade programs :)

**Comment by pwtyler** [comment]
Closed in favor of #197

**Pull request closed without merging**
