### PR TITLE
Update to drupal/drupal 7.41

### PR DESCRIPTION
**Pull request by pantheon-upstream**
This PR was created by the create-update-pr script.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Instructions to test:

Create a new Drupal 7 site for testing "d7test" (name to suit)
Clone the git repository on your local system
cd d7test
git remote add drops-7 git@github.com:pantheon-systems/drops-7.git
git fetch drops-7
git merge drops-7/update-7.41
git push origin master

Visit your site, step through the installer pages, visit the Status page, test basic functionality.

**Comment by nataliejeremy** [comment]
Worked for me--thanks @greg-1-anderson Greg. 
screen shot 2015-10-21 at 2 06 51 pm

**Comment by greg-1-anderson** [comment]
Excellent, @nataliejeremy. Did you also do some in-browser testing of your site to make sure it was still operating well?

**Comment by nataliejeremy** [comment]
@greg-1-anderson It was just a test site, but everything seems to be fine.

**Comment by koppieesq** [comment]
+1 from me too.  Did an install and a web test, including browsing, some admin pages, login, and "status report."  Don't see any smoke . . .

**Pull request closed without merging**
