### PR TITLE
[CMSP-954] Update default PHP to 8.2

### PR DESCRIPTION
**Pull request by pwtyler**
Supported as of 7.92.

https://www.drupal.org/docs/7/system-requirements/php-requirements-for-drupal-7

----
Related: https://github.com/pantheon-systems/WordPress/pull/389
https://getpantheon.atlassian.net/browse/CMSP-954

### CODE REVIEW

**Comment by pwtyler** [comment]
For CR, the ci diff is as follows:
```
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 6dd82890e..de7e5e7ea 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,11 +2,12 @@ version: 2
 jobs:
     test:
         docker:
-          - image: quay.io/pantheon-public/build-tools-ci:8.x-php7.4
+          - image: quay.io/pantheon-public/build-tools-ci:8.x-php8.2
         working_directory: ~/work/d7
         environment:
           TZ: "/usr/share/zoneinfo/America/Los_Angeles"
           TERM: dumb
+          TERMINUS_SITE: ci-update-drops-7
         steps:
             - checkout
             - run:
diff --git a/.circleci/features/phpversion.feature b/.circleci/features/phpversion.feature
index 240d40201..650dce62e 100644
--- a/.circleci/features/phpversion.feature
+++ b/.circleci/features/phpversion.feature
@@ -7,4 +7,4 @@ Feature: Check php version
   Scenario: Check the php version in the phpinfo output
     Given I am logged in as a user with the "administrator" role
     And I am on "/admin/reports/status/php"
-    Then I should see "PHP Version 7.4."
+    Then I should see "PHP Version 8.2."
diff --git a/.circleci/prepare.sh b/.circleci/prepare.sh
index 35565635c..30010adcf 100755
--- a/.circleci/prepare.sh
+++ b/.circleci/prepare.sh
@@ -22,5 +22,12 @@ terminus env:wake -n "$TERMINUS_SITE.dev"
 # Create a new environment for this particular test run.
 ###
 terminus build:env:create -n "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes
+terminus connection:set "${TERMINUS_SITE}.${TERMINUS_ENV}" git
+echo "" >> pantheon.yml
+git add pantheon.yml
+git commit -m "no-op pantheon.yml"
+terminus build:env:push "${TERMINUS_SITE}.${TERMINUS_ENV}"
+
+terminus connection:set "${TERMINUS_SITE}.${TERMINUS_ENV}" sftp
 terminus env:wake -n "$TERMINUS_SITE.$TERMINUS_ENV"
 terminus drush -n "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y
```

**Review by greg-1-anderson — APPROVED** [review]
Approved, but recommend that you force-push the .circleci changes to the default branch, and then rebase here so that the PR only contains the php version change.

**Comment by pwtyler** [comment]
Yep, that's how I will go about it. CI tests on default will be broken until this is merged.

**Review by greg-1-anderson — APPROVED** [review]
LGTM

**Pull request merged**
