### PR TITLE
Drupal core 7.78 security update

### PR DESCRIPTION
**Pull request by uberhacker**
Trying to speed this up a bit. :)

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
❤️  the community, but we can't accept PRs for security releases from external sources.

**Comment by uberhacker** [comment]
It's open source code.

**Comment by greg-1-anderson** [comment]
Yes, but it would need to be confirmed that this PR matches the upstream. This PR is pretty simple, but a good example is a composer.lock file that could load completely different code from a different source.

**Comment by uberhacker** [comment]
So basically, you are just waiting until the Pressflow upstream is updated first?

**Pull request closed without merging**
